version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080" # Esponiamo solo il gateway all'esterno
    depends_on:
      - service1
      - frontend
    networks:
      - app-network

  service1:
    build: ./service1
    # Non esponiamo la porta su host, il servizio è raggiungibile dal gateway tramite il networking interno
    expose:
      - "8081"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./UI
    # Esposto internamente (non su host), accessibile solo dal gateway
    expose:
      - "51869"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge