spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8081
          predicates:
            - Path=/service1/**
        - id: frontend
          uri: http://localhost:80
          predicates:
            # Con questa route si escludono le richieste che iniziano con /service1
            - Path=/{segment:^(?!service1).*$}
